version: '3.9'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    container_name: web-rails
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
